CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL);
CREATE TABLE tracks(id TEXT PRIMARY KEY, json TEXT NOT NULL, cached_at INTEGER NOT NULL);
CREATE TABLE track_sources(provider TEXT NOT NULL, provider_id TEXT NOT NULL, track_id TEXT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE, availability TEXT NOT NULL, url TEXT, PRIMARY KEY(provider,provider_id));
CREATE TABLE artists(id TEXT PRIMARY KEY, json TEXT NOT NULL);
CREATE TABLE artist_sources(provider TEXT NOT NULL, provider_id TEXT NOT NULL, artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE, PRIMARY KEY(provider,provider_id));
CREATE TABLE playlists(id TEXT PRIMARY KEY, title TEXT NOT NULL, artwork TEXT, created_at INTEGER NOT NULL);
CREATE TABLE playlist_tracks(playlist_id TEXT NOT NULL REFERENCES playlists(id) ON DELETE CASCADE, position INTEGER NOT NULL, track_id TEXT NOT NULL REFERENCES tracks(id), PRIMARY KEY(playlist_id,position));
CREATE TABLE favorites(track_id TEXT PRIMARY KEY REFERENCES tracks(id) ON DELETE CASCADE, added_at INTEGER NOT NULL);
CREATE TABLE history(id INTEGER PRIMARY KEY AUTOINCREMENT, track_id TEXT NOT NULL REFERENCES tracks(id) ON DELETE CASCADE, played_at INTEGER NOT NULL);
CREATE INDEX history_recent ON history(played_at DESC);
CREATE TABLE providers(id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1);
INSERT INTO providers VALUES('soundcloud',1);
CREATE TABLE provider_accounts(provider TEXT PRIMARY KEY REFERENCES providers(id), user_id TEXT, profile_json TEXT);
CREATE TABLE queue(singleton INTEGER PRIMARY KEY CHECK(singleton=1), json TEXT NOT NULL, position_ms INTEGER NOT NULL DEFAULT 0);
CREATE TABLE settings(key TEXT PRIMARY KEY, json TEXT NOT NULL);
CREATE TABLE cache_metadata(key TEXT PRIMARY KEY, kind TEXT NOT NULL, size_bytes INTEGER NOT NULL, touched_at INTEGER NOT NULL);
CREATE TABLE installation(singleton INTEGER PRIMARY KEY CHECK(singleton=1), installation_id TEXT NOT NULL, platform TEXT NOT NULL, app_version TEXT NOT NULL, first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL);
CREATE TABLE reson_account(singleton INTEGER PRIMARY KEY CHECK(singleton=1), user_id TEXT NOT NULL, username TEXT NOT NULL, avatar TEXT, created_at INTEGER NOT NULL);
INSERT INTO schema_migrations VALUES(1,unixepoch());
