import {useEffect,useState} from 'react';
import {ExternalLink,FileText,HardDrive,ShieldCheck} from 'lucide-react';
import {act,call,installation,notify,original,useProviders,useSettings} from '../stores/core';
import type {Settings} from '../stores/types';
export function SettingsView() {
 const settings=useSettings();const providers=useProviders();const [cache,setCache]=useState(0);const [devices,setDevices]=useState<{id:string;name:string}[]>([{id:'auto',name:'System default'}]);const [discordId,setDiscordId]=useState(settings.discord_application_id);const [status,setStatus]=useState('');
 useEffect(()=>{void call<number>('cache_size').then(setCache).catch(()=>{});void call<{id:string;name:string}[]>('audio_devices').then(setDevices).catch(()=>{});},[]);
 const update=(patch:Partial<Settings>)=>act('update_settings',{settings:{...settings,...patch}});
 const exportLogs=async()=>{try{setStatus(await call<string>('export_diagnostics'));notify('Diagnostics saved. Open the path shown in Settings.');}catch(e){notify(String(e));}};
 return <div className="page"><header className="page-title"><div><span className="eyebrow">Make Reson yours</span><h1>Settings</h1></div></header><div className="settings-scroll"><section className="settings-section"><h2>Audio</h2><div className="setting-row"><div><strong>Output device</strong><p>System default follows the Windows default audio device.</p></div><select aria-label="Audio output" value={settings.audio_device} onChange={e=>update({audio_device:e.target.value})}>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><p className="setting-note">Native libmpv playback · AAC HLS streaming · Close exits Reson; minimize keeps music playing.</p></section>
 <section className="settings-section"><h2>Connected sources</h2>{providers.map(p=><div className="setting-row" key={p.id}><div><strong>{p.display_name}</strong><p>Public guest access. Tracks, artists, playlists and related music.</p></div><span className="connection-state">Guest</span></div>)}<p className="setting-note">SoundCloud login needs a registered application and a secure token service. Authentication is unavailable in this release. Reson favorites and playlists stay local.</p></section>
 <section className="settings-section"><h2>Reson account</h2><div className="setting-row"><div><strong>Guest on this device</strong><p>No account needed to play public music. Account synchronization is planned.</p></div><ShieldCheck size={22}/></div></section>
 <section className="settings-section"><h2>Discord Rich Presence</h2><div className="setting-row"><div><strong>Share listening activity with Discord</strong><p>Uses local Discord desktop IPC. No listening data goes to a Reson server.</p></div><input type="checkbox" aria-label="Discord Rich Presence" checked={settings.discord_presence} disabled={!settings.discord_application_id} onChange={e=>update({discord_presence:e.target.checked})}/></div><div className="setting-row"><div><strong>Discord application ID</strong><p>Required until Reson has its own registered Discord application.</p></div><form className="inline-form" onSubmit={e=>{e.preventDefault();update({discord_application_id:discordId.trim()});}}><input aria-label="Discord application ID" value={discordId} onChange={e=>setDiscordId(e.target.value)} placeholder="Application ID"/><button className="secondary">Save</button></form></div></section>
 <section className="settings-section"><h2>Cache</h2><div className="setting-row"><div><strong><HardDrive size={15}/>Artwork cache</strong><p>{(cache/1024/1024).toFixed(1)} MB used. Audio streams are never saved to the cache.</p></div><button className="secondary" onClick={()=>{void call('clear_cache').then(()=>setCache(0)).catch(e=>notify(String(e)));}}>Clear cache</button></div><div className="setting-row"><div><strong>Maximum cache size</strong><p>Older artwork is removed automatically.</p></div><select aria-label="Cache limit" value={settings.cache_limit_mb} onChange={e=>update({cache_limit_mb:Number(e.target.value)})}>{[32,64,128,256,512,1024,2048].map(n=><option key={n} value={n}>{n} MB</option>)}</select></div></section>
 <section className="settings-section"><h2>Privacy</h2><div className="setting-row"><div><strong>Anonymous usage telemetry</strong><p>Disabled. This build has no collection endpoint and sends no usage telemetry.</p></div><span className="connection-state">Off</span></div><p className="setting-note">Installation ID is random, never HWID-derived. Searches and music requests go directly to SoundCloud. Listening history and library stay on this device.</p><p className="monospace">Installation: {installation.get()?.installation_id}</p></section>
 <section className="settings-section"><h2>About</h2><div className="setting-row"><div><strong>Reson 0.1.0</strong><p>MIT · Windows desktop music player</p></div><button className="secondary" onClick={()=>original('https://github.com/atlasru/reson')}><ExternalLink size={15}/>Repository</button></div><div className="setting-row"><div><strong>Diagnostics</strong><p>Provider status, audio and storage errors. Tokens and stream URLs excluded.</p></div><button className="secondary" onClick={()=>void exportLogs()}><FileText size={15}/>Export</button></div>{status&&<p className="diagnostic-path">{status}</p>}<p className="setting-note">Space: play/pause · Alt ←/→: previous/next · Ctrl K: search · Ctrl Q: queue · Ctrl ↑/↓: volume</p></section>
 </div></div>;
}
