import {useState} from 'react';
import {ArrowDown,ArrowUp,GripVertical,Play,Trash2,X} from 'lucide-react';
import {Artwork} from '../components/Artwork';
import {Empty} from '../components/States';
import {act,useQueue} from '../stores/core';
export function QueuePanel({close}:{close:()=>void}) {
 const queue=useQueue();const [dragging,setDragging]=useState<string|null>(null);
 return <aside className="queue-panel"><header><div><h2>Queue</h2><small>{queue.entries.length} tracks{queue.shuffle?' · Shuffled':''}</small></div><button className="icon" title="Close queue" onClick={close}><X size={18}/></button></header><div className="queue-list">{queue.entries.length===0?<Empty title="Your queue is empty" detail="Add tracks from their action menus."/>:queue.entries.map((e,index)=><div key={e.entry_id} className={`queue-item ${e.entry_id===queue.current?'current':''} ${dragging===e.entry_id?'dragging':''}`} draggable onDragStart={event=>{setDragging(e.entry_id);event.dataTransfer.setData('text/plain',e.entry_id);event.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragging(null)} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='move';}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData('text/plain');if(queue.entries.some(e=>e.entry_id===id))act('queue_reorder',{entryId:id,to:index});setDragging(null);}} onDoubleClick={()=>act('queue_select',{id:e.entry_id})}><GripVertical size={14} className="grip"/><Artwork url={e.track.artwork}/><div className="queue-title"><strong>{e.track.title}</strong><small>{e.track.artists.map(a=>a.name).join(', ')}</small></div><div className="queue-actions"><button className="icon" title="Play queue entry" onClick={()=>act('queue_select',{id:e.entry_id})}><Play size={13}/></button><button className="icon" title="Move up" disabled={index===0} onClick={()=>act('queue_reorder',{entryId:e.entry_id,to:index-1})}><ArrowUp size={13}/></button><button className="icon" title="Move down" disabled={index===queue.entries.length-1} onClick={()=>act('queue_reorder',{entryId:e.entry_id,to:index+1})}><ArrowDown size={13}/></button><button className="icon" title="Remove queue entry" onClick={()=>act('queue_remove',{id:e.entry_id})}><X size={13}/></button></div></div>)}</div>{queue.entries.length>0&&<button className="secondary clear-queue" onClick={()=>act('queue_clear')}><Trash2 size={14}/>Clear queue</button>}</aside>;
}
